impr.

diff --git a/installscript b/installscript
--- a/installscript
+++ b/installscript
@@ -43,11 +43,15 @@ echo 'Install homebrew'
 echo '----------------'
 echo install homebrew
 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
+echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >>$HOME/.zprofile
 eval "$(/opt/homebrew/bin/brew shellenv)"
 
 echo 'Install NVM'
 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"                   # This loads nvm
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
 
 echo 'Install node'
 echo '------------'
@@ -106,9 +110,8 @@ echo '----------------'
 EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
 php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
 ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
-if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
-then
-    >&2 echo 'ERROR: Invalid installer checksum'
+if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]; then
+    echo >&2 'ERROR: Invalid installer checksum'
     rm composer-setup.php
     exit 1
 fi
@@ -152,7 +155,7 @@ echo '---------------------'
 composer global require laravel/valet
 valet install
 
-ln -s $HOME/.dotfiles/misc/php-limits.ini /opt/homebrew/etc/php/8.1/conf.d/php-z-custom-limits.ini
+ln -s $HOME/.dotfiles/misc/php-limits.ini /opt/homebrew/etc/php/8.2/conf.d/php-z-custom-limits.ini
 
 echo 'Install mariadb'
 echo '-------------'
@@ -175,6 +178,10 @@ echo 'Install thefuck'
 echo '------------'
 brew install thefuck
 
+echo 'Install thefuck'
+echo '------------'
+brew install ruby
+
 echo 'Install python'
 echo '------------'
 brew install python
@@ -195,6 +202,10 @@ echo 'Install watchman'
 echo '--------------'
 brew install watchman
 
+echo 'Install k9s kubernetes'
+echo '--------------'
+brew install derailed/k9s/k9s kubectl helm
+
 echo 'Install ngrok'
 echo '--------------'
 brew install ngrok/ngrok/ngrok
@@ -203,6 +214,11 @@ echo 'Install zsh plugins: autosuggestions, autojump'
 echo '---------------------------'
 brew install zsh-autosuggestions autojump
 
+echo 'Install ddev'
+echo '---------------------------'
+brew install drud/ddev/ddev
+mkcert -install
+
 echo 'Install cocoapods'
 echo '--------------'
 brew install cocoapods
@@ -210,18 +226,6 @@ brew install cocoapods
 echo 'Install Vue CLI'
 echo '--------------'
 yarn global add @vue/cli-init
-
-echo 'Install pnpm'
-echo '--------------'
-yarn global add pnpm
-
-echo 'Install jest'
-echo '--------------'
-yarn global add jest
-
-echo 'Install expo-cli'
-echo '--------------'
-npm install --global expo-cli
 
 echo 'Install Google Fonts'
 echo '--------------'
@@ -240,7 +244,6 @@ echo 'Init Git'
 git config --global init.defaultBranch main
 git config --global push.default current
 
-
 echo '++++++++++++++++++++++++++++++'
 echo '++++++++++++++++++++++++++++++'
 echo 'All done!'
@@ -251,7 +254,7 @@ echo '1. Make sure dropbox is running first. If you have not backed up via Macku
 echo '2. Set some sensible os x defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
 echo '3. Install some helpful apps by running: $HOME/.dotfiles/macos/apps.sh'
 echo '4. Make a .dotfiles-custom/shell/.aliases for your personal commands'
-echo '5. Office 365, Cloudya and Sonos can not be installed automatically. Please do to manually if you want to.'
+echo '5. Office 365, Cloudya, 1Password, TermHere, ImageOptim and Sonos can not be installed automatically. Please do to manually if you want to.'
 
 echo '++++++++++++++++++++++++++++++'
 echo '++++++++++++++++++++++++++++++'
